### ISSUE TITLE
Falta de UCs

### ISSUE THREAD

**Issue by DevRafonalde** [vpedrota/montador-de-grades#7]
Não sei se tem mais alguma. Mas senti falta da UC "RER - Cálculo em Uma Variável" no período noturno às terças, quintas e sextas das 19:00 à 21:00
![imagem_2023-08-01_093252613](https://github.com/vpedrota/montador-de-grades/assets/99509136/8f60e7fb-9876-4749-802a-724774b39198)
![image](https://github.com/vpedrota/montador-de-grades/assets/99509136/551d2a1c-847a-4954-a5a9-33b428d4ff05)
![image](https://github.com/vpedrota/montador-de-grades/assets/99509136/cb952038-4d73-4554-9696-82c865c48158)

**Comment by vpedrota** [comment]
Se as outras matérias estão aparecendo acredito ser um erro do bot de identificar as disciplinas ou essa matéria foi adicionada recentemente, vou rodar novamente o bot para identificar as disciplinas e verificar qual é o erro. Caso tenha sido adicionada recentemente isso deve resolver.
